defaults:
  - _self_
  - augmentations: symmetric.yaml
  - nn_augmentations: reconstruction.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "supcon-rhid-val" # change here for cifar10
method: "supcon"
log_path: "../scratch/ht-image-ssl/logs/"
backbone:
  name: "resnet50"
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 256
  temperature: 0.2
data:
  dataset: rhid-val
  train_path: "../rhid-2021_maxEdge500_restructured/train"
  val_path: "../rhid-2021_maxEdge500_restructured/val1"
  format: "image_folder"
  num_workers: 10
optimizer:
  name: "sgd"
  batch_size: 256
  lr: 0.4
  classifier_lr: 0.1
  weight_decay: 1e-5
scheduler:
  name: "warmup_cosine"
checkpoint_config:
  enabled: False
  dir: "../scratch/ht-image-ssl/trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 100
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16