defaults:
  - _self_
  - augmentations: reconstruction.yaml
  - nn_augmentations: no_transform.yaml
  - emb_model: resnet50.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "simclr-cifar10-gps" # change here for cifar10
method: "simclr"
gps: True
nn_key: 'feats'
log_path: "../../scratch/ht-image-ssl/logs/"
backbone:
  name: "resnet50"
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 256
  temperature: 0.2
data:
  dataset: cifar10 # change here for cifar10
  train_path: "../scratch/cifar10/"
  val_path: "../scratch/cifar10/"
  format: "image_folder"
  num_workers: 4
  filter_sim_matrix: True
  num_nns_choice: 1
  num_nns: 1
  reload_freq: 0
optimizer:
  name: "lars"
  batch_size: 256
  lr: 0.4
  classifier_lr: 0.1
  weight_decay: 1e-4
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint_config:
  enabled: False
  dir: "../../scratch/ht-image-ssl/trained_models"
  frequency: 1
auto_resume:
  enabled: False

# overwrite PL stuff
max_epochs: 1000
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16