defaults:
  - _self_
  - augmentations: reconstruction.yaml
  - emb_model: resnet50.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "simclr-E-rhidV-gnnclr" # change here for cifar10
method: "gnnclr"
gnnclr: True
nn_key: 'feats'
log_path: "../../scratch/ht-image-ssl/logs/"
backbone:
  name: "resnet18"
method_kwargs:
  proj_hidden_dim: 2048
  pred_hidden_dim: 4096
  proj_output_dim: 256
  temperature: 0.2
data:
  dataset: rhid-val
  train_path: "../scratch/rhid-2021_maxEdge500_restructured/train"
  val_path: "../scratch/rhid-2021_maxEdge500_restructured/val1"
  val2_path: "../scratch/rhid-2021_maxEdge500_restructured/val2"
  val3_path: "../scratch/rhid-2021_maxEdge500_restructured/val3"
  format: "image_folder"
  num_workers: 10
  reload_freq: 0
  num_nns: 1
  num_nns_choice: 1
  filter_sim_matrix: False
optimizer:
  name: "lars"
  batch_size: 256
  lr: 0.4
  classifier_lr: 0.1
  weight_decay: 1e-4
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint_config:
  enabled: False
  dir: "../../scratch/ht-image-ssl/trained_models"
  frequency: 1
auto_resume:
  enabled: False

# overwrite PL stuff
max_epochs: 200
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
